apiVersion: v1
kind: ServiceAccount
metadata:
  name: balance-saml
  namespace: balance-saml
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/name: balance-saml
    app.kubernetes.io/part-of: arencloud-identity
