FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:1.24

LABEL name="balance" \
      summary="Arencloud Balance demo application" \
      description="Quarkus Balance application secured by RHBK roles" \
      io.k8s.display-name="Balance" \
      io.openshift.tags="quarkus,java,balance"

ENV LANGUAGE="en_US:en" \
    JAVA_APP_JAR="/deployments/quarkus-run.jar" \
    JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

COPY --chown=0:0 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=0:0 target/quarkus-app/*.jar /deployments/
COPY --chown=0:0 target/quarkus-app/app/ /deployments/app/
COPY --chown=0:0 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080

ENTRYPOINT ["/opt/jboss/container/java/run/run-java.sh"]
