apiVersion: v1
kind: ConfigMap
metadata:
  name: balance-config
  namespace: balance
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/name: balance
    app.kubernetes.io/part-of: arencloud-identity
data:
  OIDC_AUTH_SERVER_URL: https://sso.arencloud.com/realms/arencloud
  OIDC_CLIENT_ID: balance
  QUARKUS_OIDC_TLS_TLS_CONFIGURATION_NAME: rhbk
  QUARKUS_TLS_RHBK_TRUST_STORE_PEM_CERTS: /mnt/trusted-ca-bundle/ca-bundle.crt
  DB_JDBC_URL: jdbc:postgresql://10.10.30.5:5432/balance
