apiVersion: v1
kind: ServiceAccount
metadata:
  name: balance
  namespace: balance
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/name: balance
    app.kubernetes.io/part-of: arencloud-identity
