apiVersion: v1
kind: ConfigMap
metadata:
  name: balance-config
  namespace: balance
  labels:
    app.kubernetes.io/name: balance
    app.kubernetes.io/part-of: arencloud-identity
data:
  OIDC_AUTH_SERVER_URL: https://sso.arencloud.com/realms/arencloud
  OIDC_CLIENT_ID: balance
  QUARKUS_HTTP_PROXY_PROXY_ADDRESS_FORWARDING: "true"
  QUARKUS_HTTP_PROXY_ALLOW_X_FORWARDED: "true"
  QUARKUS_OIDC_AUTHENTICATION_FORCE_REDIRECT_HTTPS_SCHEME: "true"
  DB_JDBC_URL: jdbc:postgresql://postgresql.example.invalid:5432/balance
