apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhbk-pgsql
  namespace: rhbk
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/name: rhbk
    app.kubernetes.io/component: database-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: rhbk-pgsql
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: cl03/rhbk/pgsql
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: cl03/rhbk/pgsql
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
