apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca-bundle
  namespace: rhbk
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    config.openshift.io/inject-trusted-cabundle: "true"
  labels:
    app.kubernetes.io/name: rhbk
    app.kubernetes.io/component: truststore
